### ISSUE TITLE
Inference in C++ not working

### ISSUE THREAD

**Issue by LorenzoMattia** [sashanksilwal/Capstone#5]
Hi @sashanksilwal, sorry to bother you. I am trying to do something really similar to what you did here and after a long search on the web I came across your repo. 

I built a model composed by a Sklearn Pipeline of a CountVectorizer and an SVM model with the aim of classifying some variable length strings and I exported it in ONNX format. While using this model in python with the onnxruntime library works perfectly, in C++ it always returns the exact same result. Inspecting the process I discovered that the problem is probably located in the CountVectorizer, which always returns a matrix of zeros.

Have you faced a similar problem or do you know how this could be solved?

Hoping for an answer from you, have a good day!

**Comment by sashanksilwal** [comment]
Hi @LorenzoMattia sorry for getting back to you late, haven't really been active here. I did not encounter such errors. If the issue has not been resolved yet, please provide me with the details, and I can take a look at it.

**Comment by LorenzoMattia** [comment]
Hi @sashanksilwal thank for your answer. This is the function that I wrote that is supposed to perform the inference on a vector of strings and that instead does not work:

```c++
std::vector<U> infer(std::vector<T> input)
{
	Ort::Value inputTensors{ nullptr };
	try {
		inputTensors = Ort::Value::CreateTensor<T>(
			_memoryInfo, input.data(), input.size(), _inputShape, _inShapeLen);
	}
	catch(Ort::Exception oe) {
		std::cout << "ONNX exception caught: " << oe.what() << ". Code: " << oe.GetOrtErrorCode() << ".\n";
	}

	std::vector<U> output(_outShapeSize, 0.0);
	Ort::Value outputTensors = Ort::Value::CreateTensor<U>(
		_memoryInfo, output.data(), output.size(),
		_outputShape, _outShapeLen);

	try {
		_session.Run(Ort::RunOptions{ nullptr }, _inputNames, &inputTensors,
			1, _outputNames, &outputTensors, 1);
	}
	catch (Ort::Exception oe) {
		std::cout << "ONNX exception caught: " << oe.what() << ". Code: " << oe.GetOrtErrorCode() << ".\n";
	}

	return output;
};
```

And this is how I initialize the model:

```c++
ONNXRuntime(std::vector<int64_t> inputShape, std::vector<int64_t> outputShape, const char* inputName, const char* outputName, const wchar_t modelPath[])
{
	_env = Ort::Env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, "Default");

	try {
		_session = Ort::Session(_env, modelPath, Ort::SessionOptions{ nullptr });
	}
	catch (Ort::Exception oe) {
		std::cout << "ONNX exception caught: " << oe.what() << ". Code: " << oe.GetOrtErrorCode() << ".\n";
	}

	_inputNames[0] = inputName;
	_outputNames[0] = outputName;

	// compute len and size

	// compute length of shape arrays
	_inShapeLen = inputShape.size();
	_outShapeLen = outputShape.size();

	// compute size of shape arrays
	_inShapeSize = getSize(inputShape);
	_outShapeSize = getSize(outputShape);

	_inputShape = new int64_t[_inShapeLen];
	_outputShape = new int64_t[_outShapeLen];
	std::copy(inputShape.begin(), inputShape.end(), _inputShape);
	std::copy(outputShape.begin(), outputShape.end(), _outputShape);
};
```

Let me know if you see some problems! Thank you
